version: "3.8"

services:
  # Python FastAPI Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - APP_NAME=PitchGenius API
      - APP_ENV=development
      - APP_DEBUG=true
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8000
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    restart: always

  # Redis Database Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: